# Generated by Django 2.2.1 on 2019-05-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gene_db_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('HGNC', models.CharField(max_length=255, null=True)),
                ('Entrez_Gene', models.CharField(max_length=255, null=True)),
                ('Ensembl', models.CharField(max_length=255, null=True)),
                ('UniProKB', models.CharField(max_length=255, null=True)),
                ('OMIM', models.CharField(max_length=255, null=True)),
                ('HGNC_link', models.CharField(max_length=255, null=True)),
                ('Entrez_Gene_link', models.CharField(max_length=255, null=True)),
                ('Ensembl_link', models.CharField(max_length=255, null=True)),
                ('UniProKB_link', models.CharField(max_length=255, null=True)),
                ('OMIM_link', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='genecard_description_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('summary_entrez', models.CharField(max_length=255, null=True)),
                ('summary_genecard', models.CharField(max_length=255, null=True)),
                ('summary_uniport', models.CharField(max_length=255, null=True)),
                ('summary_Tocris', models.CharField(max_length=255, null=True)),
                ('summary_CIViC', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
