# Generated by Django 2.2.1 on 2019-06-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenecardId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(blank=True, max_length=255, null=True)),
                ('subname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'genecard_id',
                'managed': False,
            },
        ),
    ]
